name: KillCommand
version: '${project.version}'
main: me.miko.killcommand.KillCommand
api-version: '1.21'
folia-supported: true
commands:
  kill:
    description: Kills yourself or another player.
    aliases:
      - suicide
    usage: /<command> [player]
permissions:
  killcommand.kill:
    description: Allows using /kill on yourself.
    default: op
  killcommand.kill.others:
    description: Allows using /kill on other players.
    default: op
